### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by NixusCN** [weflex/react-native-wechat#14]
This program appeared only in real device iPhone，it‘s ok in simulator
![image](https://cloud.githubusercontent.com/assets/4592706/12005625/ab58abdc-abea-11e5-9aa4-83ded6b629a7.png)

**Comment by yorkie** [comment]
This seems not to be relevant to library, @NixusCN could you give us more information about reproducing this bug?

**Comment by tdzl2003** [comment]
This issue is not related to this package.

You can fix it by modify `node_modules/react-native/Libraries/Devtools/setupDevtools.js` and `node_modules/react-native/Libraries/WebSocket/RCTWebSocketExecutor.m`, change`localhost` into your real IP.

Or you can simply disable debugger & devtools by build a release package (change build schema into `release`).
