### ISSUE TITLE
Use of undeclared identifier 'RCTResizeModeStretch'

### ISSUE THREAD

**Issue by quentinzhang** [weflex/react-native-wechat#40]
build failed in version 1.3.1

line 284 in RCTWeChat.m:
Use of undeclared identifier 'RCTResizeModeStretch'

Can you suggest a solution for it?

**Comment by xing-zheng** [comment]
the identifier 'RCTResizeModeStretch' is defined in "RCTResizeMode.h" witch is included by "RCTImageUtils.h", they are both reside in the directory "/node_modules/react-native/Libraries/Image".

If you install the react-native-wechat plugin by "npm install react-native-wechat --save" or "react-native link react-native-wechat" command, the "Header Search Path" options of XCode project is defined correctly, Otherwise you should add that directory into the "Header Search Path" manually.

**Comment by letmeknowhow** [comment]
I can't find anything about RCTResizeModeStretch in /node_modules/react-native/Libraries/Image.
I use RN of V0.17, do you think I have to upgrade it to a newer version?

**Comment by xing-zheng** [comment]
@letmeknowhow Please upgrade to the new version of RN.
You can edit the "/package.json" and change the react-native dependency to "^0.21.0".
delete the /node_modules/react-native
run "npm install" command

**Comment by yorkie** [comment]
Do we need upgrade the react-native version in master @xing-zheng ?

**Comment by xing-zheng** [comment]
@yorke OK, let me find the minimum react-native version that the plugin compatible with and try to update the dependency.

**Comment by yorkie** [comment]
Thanks so much @xing-zheng

**Comment by xing-zheng** [comment]
Hi @yorkie , I found that the RCTResizeMode.h file had been introduced into react-native Image library on 21 Jan 2016( facebook/react-native@21fcbbc32cc822f6d2db3f099082cac6b225cb48), and the earliest release version that contain this file is 0.20.0 witch was released on 16 Feb 2016 (facebook/react-native@6496feb61e9205baa3f25cf448c4fce912bd6250).

So, I think we should update the dependency react-native version to 0.20.0.

**Comment by yorkie** [comment]
@quentinzhang @letmeknowhow could you try with 1.3.2, that with a patch from @xing-zheng :-)

**Comment by quentinzhang** [comment]
@xing-zheng @yorkie Thanks for your kind help, will do!
